#!/bin/sh
set -e

cuid=`echo $(logname 2>/dev/null || echo $SUDO_USER)`

if [ -x /bin/systemctl ] ; then
    systemctl daemon-reload  >/dev/null || true
    sudo su $cuid -c "systemctl --user --now enable hamonikr-pcchecker.service hamonikr-pcchecker.timer"  >/dev/null || true
fi

gtk-update-icon-cache

exit 0